### ISSUE TITLE
Xbox One Store Version?

### ISSUE THREAD

**Issue by wiired24** [aboe026/boxify#63]
Hey I think boxify is great and myself and others are really enjoying it.

In saying that,  Would it be possible to submit this to the Windows Store so users could download this
and install it in Retail mode on their Xbox One? 

Thanks in advance

**Comment by aboe026** [comment]
Hi @wiired24,

It is available in the windows store: https://www.microsoft.com/en-us/store/p/boxify/9p8x40rdvgbf, or you should be able to search and find it in the Xbox One store as `Boxify`. Let me know if you're not seeing it. The only region it is currently unavailable in is China (they required some extra certification I wasn't sure of how to do at the time, will get back to that at some point...)

Enjoy!

**Comment by wiired24** [comment]
Oh, Awesome to Hear :)
