### ISSUE TITLE
releases wont install on xbox one (dev mode)

### ISSUE THREAD

**Issue by dominater01** [aboe026/boxify#76]
only releases by you guys (here at github) whatever a appxupload is the xbox one doesnt like it can you guys make it appx or appxbundle instead atm i cant build it (crappy pc)

**Comment by aboe026** [comment]
sure! Sorry it took me so long to see this :/ I'm about to put up a new version in the next day or two, I'll include .appx for all the architectures as well

**Comment by dominater01** [comment]
sweet thanks

**Comment by aboe026** [comment]
Actually I didn't realize I still had them saved off. Just uploaded the `appxbundle`'s now to the releases. Let me know if you need the straight up `.appx` as well though

**Comment by dominater01** [comment]
thanks it worked fine :)
